server:
  port: 9000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #http://192.168.75.128:8761/eureka/
   # register-with-eureka: false #是否将eureka自身作为应用注册到eureka注册中心
   # fetch-registry: false # 为true时报异常： Cannot execute request on any known server
spring:
  application:
    name: eureka-customer